name: Automatic PR description

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit messages and update PR
        uses: actions/github-script@v7
        with:
          script: |
            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            const messages = [
                    ...new Set(
                        commits.map(c => c.commit.message.split('\n')[0])
                    )
                ]
                .map(m => `- ${m}`).join('\n');
            
            const body = `## Changes\n\n${messages}`;
            
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body,
            });