name: "Quo PHP testkit"
on:
  pull_request:
    paths:
      - "src/**/*.js"
      - "initialise.js"
      - "main.html"
      - ".github/workflows/testkit.yml"
jobs:
  testkit81:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: doyensec/electronegativity-action@v1.1

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ../results

